server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway-rw
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowed-origins: "${ALLOWED_ORIGINS:http://localhost:3000,http://127.0.0.1:3000,http://101.132.179.6:3000}"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
      discovery:
        locator:
          enabled: false
      routes:
        - id: user_service_route
          uri: ${USER_SERVICE_URL:}  http://user-service:8081 # http://localhost:8081
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=0
        - id: qa_service_route
          uri: ${QA_SERVICE_URL:http://qa-service:8082 } # http://localhost:8082
          predicates:
            - Path=/api/qa/**
          filters:
            - StripPrefix=0
            - name: RequestRateLimiter
              args:
                rate-limiter: "#{@inMemoryRateLimiter}"
                key-resolver: "#{@ipKeyResolver}"
                replenish-rate: 10000
                burst-capacity: 100000
                requested-tokens: 1

logging:
  file:
    name: application.log
    path: logs
  level:
    com.ai.qa.service: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  charset:
    console: UTF-8
    file: UTF-8

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      enabled: true
      show-details: when_authorized
    info:
      enabled: true
    metrics:
      enabled: false
  metrics:
    enable:
      process: false
      system: false
